vim.api.nvim_create_user_command("ToggleQuickfix", ToggleQuickfix, {})
vim.api.nvim_create_user_command("SoloBuf", SoloBuf, {})
vim.api.nvim_create_user_command("ToggleWrap", ToggleWrap, {})
vim.api.nvim_create_user_command("ClearReg", ClearReg, {})
vim.api.nvim_create_user_command("ToggleFrame", ToggleFrame, {})
vim.api.nvim_create_user_command("MSG", MSG, {})

vim.cmd.cnoreabbrev('hs', 'split')
vim.cmd.cnoreabbrev('vs', 'vsplit')
vim.cmd.cnoreabbrev('msg', 'MSG')
vim.cmd.cnoreabbrev('it', 'set spelllang=it')
vim.cmd.cnoreabbrev('git', '!git')
vim.cmd.cnoreabbrev('typos', '!typos')
