require("config.opt")
require("config.globals")
require("config.lazy")
require("config.functions")
require("config.diagnostic")
require("config.autocmd")
require("config.commands")
require("config.keymap")
