vim.opt.termguicolors = true
vim.opt.clipboard = "unnamedplus"
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.spell = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.list = true
vim.opt.listchars:append "trail:·"
vim.opt.fillchars:append { eob = "·" }
vim.opt.smartindent = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.scrolloff = 100
vim.opt.virtualedit = ""
vim.opt.signcolumn = "auto"
vim.opt.updatetime = 250
vim.opt.laststatus = 3
vim.opt.winborder = "rounded"
